name: game-engine
version: 0.1.0.0
github: "student/game-engine"
license: MIT
author: "Your Group"
maintainer: "your@email.com"
copyright: "2025"

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - scotty
  - aeson
  - text
  - wai
  - warp
  - wai-cors
  - wai-extra

executables:
  game-engine:
    main: Main.hs
    source-dirs: .
    ghc-options:
      - -Wall
